-- ===================================================================
--  Flyway Migration: V1__init_schema.sql
--  Description: Initial schema for Friseur application
--  Author: Igor Prokhorchuk
--  Date: 2025-11-09
-- ===================================================================

-- Set schema
CREATE SCHEMA IF NOT EXISTS public;

-- ================================================================
-- Table: app_user
-- ================================================================
CREATE TABLE IF NOT EXISTS public.app_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) UNIQUE,
    user_name VARCHAR(255)
);

-- ================================================================
-- Table: appointment
-- ================================================================
CREATE TABLE IF NOT EXISTS public.appointment (
    appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_status VARCHAR(255) CHECK (appointment_status IN ('UPCOMING', 'COMPLETED', 'CANCELLED')),
    client_name VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    service_type VARCHAR(255),
    user_id INTEGER REFERENCES public.app_user(user_id) ON DELETE CASCADE
);

-- ================================================================
-- Table: schedule
-- ================================================================
CREATE TABLE IF NOT EXISTS public.schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

-- ================================================================
-- Table: slot
-- ================================================================
CREATE TABLE IF NOT EXISTS public.slot (
    slot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_status VARCHAR(255) CHECK (slot_status IN ('AVAILABLE', 'RESERVED', 'PAID', 'CANCELLED', 'CLOSED', 'HIDDEN')),
    time_slot TIMESTAMP(6) WITHOUT TIME ZONE,
    appointment_id BIGINT UNIQUE REFERENCES public.appointment(appointment_id) ON DELETE CASCADE
);

-- ================================================================
-- Table: user_roles
-- ================================================================
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id INTEGER NOT NULL REFERENCES public.app_user(user_id) ON DELETE CASCADE,
    role VARCHAR(255),
    PRIMARY KEY (user_id, role)
);

-- ================================================================
-- Indexes
-- ================================================================
CREATE INDEX IF NOT EXISTS idx_appointment_user_id ON public.appointment(user_id);
CREATE INDEX IF NOT EXISTS idx_slot_appointment_id ON public.slot(appointment_id);

-- ================================================================
-- Data integrity: ensure schema exists for application startup
-- ================================================================
COMMENT ON TABLE public.app_user IS 'Stores all registered users';
COMMENT ON TABLE public.appointment IS 'Appointments associated with users and slots';
COMMENT ON TABLE public.schedule IS 'Working day ranges for the salon';
COMMENT ON TABLE public.slot IS 'Individual time slots for appointments';
COMMENT ON TABLE public.user_roles IS 'User roles for authorization';

