-- ===================================================================
--  Flyway Migration: V2__add_token_blacklist.sql
--  Description: Add token_blacklist table for JWT token invalidation
--  Author: Vibe Code
--  Date: 2025-01-18
-- ===================================================================

-- ================================================================
-- Table: token_blacklist
-- ================================================================
CREATE TABLE IF NOT EXISTS public.token_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(1000) NOT NULL UNIQUE,
    blacklisted_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    token_type VARCHAR(50),
    username VARCHAR(255)
);

-- ================================================================
-- Indexes for token_blacklist
-- ================================================================
CREATE INDEX IF NOT EXISTS idx_token_blacklist_token ON public.token_blacklist(token);
CREATE INDEX IF NOT EXISTS idx_token_blacklist_username ON public.token_blacklist(username);
CREATE INDEX IF NOT EXISTS idx_token_blacklist_expires_at ON public.token_blacklist(expires_at);

-- ================================================================
-- Comment
-- ================================================================
COMMENT ON TABLE public.token_blacklist IS 'Stores blacklisted JWT tokens for logout and security invalidation';
COMMENT ON COLUMN public.token_blacklist.token IS 'The JWT token value that has been blacklisted';
COMMENT ON COLUMN public.token_blacklist.blacklisted_at IS 'When the token was added to the blacklist';
COMMENT ON COLUMN public.token_blacklist.expires_at IS 'When the blacklist entry expires (same as token expiration)';
COMMENT ON COLUMN public.token_blacklist.token_type IS 'Type of token: access or refresh';
COMMENT ON COLUMN public.token_blacklist.username IS 'Username associated with the blacklisted token';
